### ISSUE TITLE
pvl_readtmy3 --> call to parsePre/Post2015 overwrites header data (simple fix)

### ISSUE THREAD

**Issue by shirubana** [sandialabs/MATLAB_PV_LIB#12]
On function : https://github.com/sandialabs/MATLAB_PV_LIB/blob/master/pvl_readtmy3.m
Move line 151 to 161 to after the "end" of  "if isempty(strfind(char(DataLines{1,1}{1,1}), 'PresWth'))" in line 178.
Otherwise output TMYData won't have all that header information.

**Comment by cwhanse** [comment]
Good catch, thanks!  We'll fix this in the next release.

**Comment by cwhanse** [comment]
Closed by v1.4 release
