### ISSUE TITLE
Incorrect value for dEgdT in pvl_calcparams_CEC

### ISSUE THREAD

**Issue by DanRiley** [sandialabs/MATLAB_PV_LIB#32]
In function “pvl_calcparams_CEC.m” the parameter dEgdT is set to 0.00002677 (i.e.  2.677e-5).
According to the documentation and the cited paper “[1] W. De Soto et al., "Improvement and validation of a model for photovoltaic array performance", Solar Energy, vol 80, pp. 78-88, 2006.”, the value should be one order of magnitude higher (2.677e-4). The Python version of the library also implements the larger value for dEgdT.

Thanks to Patrick for finding the bug.

**Comment by cwhanse** [comment]
Confirmed and corrected. Thanks @DanRiley
